### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by rafaeleyng** [hugcruz/parprog1#2]
Hi there

I am curious to run the examples, but I don't know anything about Scala. I started doing the course but had to stop. Still, I don't know how to run the examples.

Would be nice to have a super simple "how to run" in the README

**Comment by hugcruz** [comment]
Hi,

This repo started as a simple backup of my files while I was doing the course, so I never wrote a properly readme. I have done that now.

Please have a look and let me know what you think.

As a side note, if you are new to Scala, I think you should start with "Functional Programming Principles in Scala", where the basics are explained. In the "Parallel Programming" course, they assume experience with the language and tools.

**Comment by rafaeleyng** [comment]
Hi @hugcruz , thanks for the response. I did follow your README and everything worked just fine. 

Thanks again 👍
